// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: jobqueue.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "";

export interface CreateQueueRequest {
  queueName: string;
}

export interface PushRequest {
  queueId: string;
  jobData: { [key: string]: any } | undefined;
  metadata?: { [key: string]: any } | undefined;
}

export interface ListenQueueRequest {
  queue: string;
  concurrency: number;
}

export interface DeleteQueueRequest {
  queueId: string;
}

export interface ListenQueueStreamResponse {
  queueConnectResponse?: QueueConnectResponse | undefined;
  jobDataResponse?: JobDataResponse | undefined;
}

export interface JobDataResponse {
  jobData: { [key: string]: any } | undefined;
}

export interface QueueConnectResponse {
  workerId: string;
}

export interface SuccessBoolResponse {
  success: boolean;
}

export interface HearthbeatRequest {
  worker: string;
}

export interface JobInfoRequest {
  jobID: string;
  workerID: string;
}

function createBaseCreateQueueRequest(): CreateQueueRequest {
  return { queueName: "" };
}

export const CreateQueueRequest: MessageFns<CreateQueueRequest> = {
  encode(message: CreateQueueRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueName !== "") {
      writer.uint32(10).string(message.queueName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateQueueRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateQueueRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.queueName = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CreateQueueRequest {
    return { queueName: isSet(object.queueName) ? globalThis.String(object.queueName) : "" };
  },

  toJSON(message: CreateQueueRequest): unknown {
    const obj: any = {};
    if (message.queueName !== "") {
      obj.queueName = message.queueName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateQueueRequest>, I>>(base?: I): CreateQueueRequest {
    return CreateQueueRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateQueueRequest>, I>>(object: I): CreateQueueRequest {
    const message = createBaseCreateQueueRequest();
    message.queueName = object.queueName ?? "";
    return message;
  },
};

function createBasePushRequest(): PushRequest {
  return { queueId: "", jobData: undefined, metadata: undefined };
}

export const PushRequest: MessageFns<PushRequest> = {
  encode(message: PushRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueId !== "") {
      writer.uint32(10).string(message.queueId);
    }
    if (message.jobData !== undefined) {
      Struct.encode(Struct.wrap(message.jobData), writer.uint32(18).fork()).join();
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PushRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePushRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.queueId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.jobData = Struct.unwrap(Struct.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PushRequest {
    return {
      queueId: isSet(object.queueId) ? globalThis.String(object.queueId) : "",
      jobData: isObject(object.jobData) ? object.jobData : undefined,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message: PushRequest): unknown {
    const obj: any = {};
    if (message.queueId !== "") {
      obj.queueId = message.queueId;
    }
    if (message.jobData !== undefined) {
      obj.jobData = message.jobData;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PushRequest>, I>>(base?: I): PushRequest {
    return PushRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PushRequest>, I>>(object: I): PushRequest {
    const message = createBasePushRequest();
    message.queueId = object.queueId ?? "";
    message.jobData = object.jobData ?? undefined;
    message.metadata = object.metadata ?? undefined;
    return message;
  },
};

function createBaseListenQueueRequest(): ListenQueueRequest {
  return { queue: "", concurrency: 0 };
}

export const ListenQueueRequest: MessageFns<ListenQueueRequest> = {
  encode(message: ListenQueueRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queue !== "") {
      writer.uint32(10).string(message.queue);
    }
    if (message.concurrency !== 0) {
      writer.uint32(16).int32(message.concurrency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListenQueueRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListenQueueRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.queue = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.concurrency = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ListenQueueRequest {
    return {
      queue: isSet(object.queue) ? globalThis.String(object.queue) : "",
      concurrency: isSet(object.concurrency) ? globalThis.Number(object.concurrency) : 0,
    };
  },

  toJSON(message: ListenQueueRequest): unknown {
    const obj: any = {};
    if (message.queue !== "") {
      obj.queue = message.queue;
    }
    if (message.concurrency !== 0) {
      obj.concurrency = Math.round(message.concurrency);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListenQueueRequest>, I>>(base?: I): ListenQueueRequest {
    return ListenQueueRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListenQueueRequest>, I>>(object: I): ListenQueueRequest {
    const message = createBaseListenQueueRequest();
    message.queue = object.queue ?? "";
    message.concurrency = object.concurrency ?? 0;
    return message;
  },
};

function createBaseDeleteQueueRequest(): DeleteQueueRequest {
  return { queueId: "" };
}

export const DeleteQueueRequest: MessageFns<DeleteQueueRequest> = {
  encode(message: DeleteQueueRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueId !== "") {
      writer.uint32(10).string(message.queueId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteQueueRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseDeleteQueueRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.queueId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): DeleteQueueRequest {
    return { queueId: isSet(object.queueId) ? globalThis.String(object.queueId) : "" };
  },

  toJSON(message: DeleteQueueRequest): unknown {
    const obj: any = {};
    if (message.queueId !== "") {
      obj.queueId = message.queueId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteQueueRequest>, I>>(base?: I): DeleteQueueRequest {
    return DeleteQueueRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteQueueRequest>, I>>(object: I): DeleteQueueRequest {
    const message = createBaseDeleteQueueRequest();
    message.queueId = object.queueId ?? "";
    return message;
  },
};

function createBaseListenQueueStreamResponse(): ListenQueueStreamResponse {
  return { queueConnectResponse: undefined, jobDataResponse: undefined };
}

export const ListenQueueStreamResponse: MessageFns<ListenQueueStreamResponse> = {
  encode(message: ListenQueueStreamResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueConnectResponse !== undefined) {
      QueueConnectResponse.encode(message.queueConnectResponse, writer.uint32(10).fork()).join();
    }
    if (message.jobDataResponse !== undefined) {
      JobDataResponse.encode(message.jobDataResponse, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListenQueueStreamResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseListenQueueStreamResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.queueConnectResponse = QueueConnectResponse.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.jobDataResponse = JobDataResponse.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ListenQueueStreamResponse {
    return {
      queueConnectResponse: isSet(object.queueConnectResponse)
        ? QueueConnectResponse.fromJSON(object.queueConnectResponse)
        : isSet(object.queue_connect_response)
        ? QueueConnectResponse.fromJSON(object.queue_connect_response)
        : undefined,
      jobDataResponse: isSet(object.jobDataResponse)
        ? JobDataResponse.fromJSON(object.jobDataResponse)
        : isSet(object.job_data_response)
        ? JobDataResponse.fromJSON(object.job_data_response)
        : undefined,
    };
  },

  toJSON(message: ListenQueueStreamResponse): unknown {
    const obj: any = {};
    if (message.queueConnectResponse !== undefined) {
      obj.queueConnectResponse = QueueConnectResponse.toJSON(message.queueConnectResponse);
    }
    if (message.jobDataResponse !== undefined) {
      obj.jobDataResponse = JobDataResponse.toJSON(message.jobDataResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListenQueueStreamResponse>, I>>(base?: I): ListenQueueStreamResponse {
    return ListenQueueStreamResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListenQueueStreamResponse>, I>>(object: I): ListenQueueStreamResponse {
    const message = createBaseListenQueueStreamResponse();
    message.queueConnectResponse = (object.queueConnectResponse !== undefined && object.queueConnectResponse !== null)
      ? QueueConnectResponse.fromPartial(object.queueConnectResponse)
      : undefined;
    message.jobDataResponse = (object.jobDataResponse !== undefined && object.jobDataResponse !== null)
      ? JobDataResponse.fromPartial(object.jobDataResponse)
      : undefined;
    return message;
  },
};

function createBaseJobDataResponse(): JobDataResponse {
  return { jobData: undefined };
}

export const JobDataResponse: MessageFns<JobDataResponse> = {
  encode(message: JobDataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobData !== undefined) {
      Struct.encode(Struct.wrap(message.jobData), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobDataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseJobDataResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.jobData = Struct.unwrap(Struct.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): JobDataResponse {
    return { jobData: isObject(object.jobData) ? object.jobData : undefined };
  },

  toJSON(message: JobDataResponse): unknown {
    const obj: any = {};
    if (message.jobData !== undefined) {
      obj.jobData = message.jobData;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobDataResponse>, I>>(base?: I): JobDataResponse {
    return JobDataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobDataResponse>, I>>(object: I): JobDataResponse {
    const message = createBaseJobDataResponse();
    message.jobData = object.jobData ?? undefined;
    return message;
  },
};

function createBaseQueueConnectResponse(): QueueConnectResponse {
  return { workerId: "" };
}

export const QueueConnectResponse: MessageFns<QueueConnectResponse> = {
  encode(message: QueueConnectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workerId !== "") {
      writer.uint32(10).string(message.workerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueConnectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseQueueConnectResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.workerId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): QueueConnectResponse {
    return { workerId: isSet(object.workerId) ? globalThis.String(object.workerId) : "" };
  },

  toJSON(message: QueueConnectResponse): unknown {
    const obj: any = {};
    if (message.workerId !== "") {
      obj.workerId = message.workerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueueConnectResponse>, I>>(base?: I): QueueConnectResponse {
    return QueueConnectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueueConnectResponse>, I>>(object: I): QueueConnectResponse {
    const message = createBaseQueueConnectResponse();
    message.workerId = object.workerId ?? "";
    return message;
  },
};

function createBaseSuccessBoolResponse(): SuccessBoolResponse {
  return { success: false };
}

export const SuccessBoolResponse: MessageFns<SuccessBoolResponse> = {
  encode(message: SuccessBoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuccessBoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSuccessBoolResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.success = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SuccessBoolResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: SuccessBoolResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SuccessBoolResponse>, I>>(base?: I): SuccessBoolResponse {
    return SuccessBoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SuccessBoolResponse>, I>>(object: I): SuccessBoolResponse {
    const message = createBaseSuccessBoolResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseHearthbeatRequest(): HearthbeatRequest {
  return { worker: "" };
}

export const HearthbeatRequest: MessageFns<HearthbeatRequest> = {
  encode(message: HearthbeatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.worker !== "") {
      writer.uint32(10).string(message.worker);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HearthbeatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHearthbeatRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.worker = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): HearthbeatRequest {
    return { worker: isSet(object.worker) ? globalThis.String(object.worker) : "" };
  },

  toJSON(message: HearthbeatRequest): unknown {
    const obj: any = {};
    if (message.worker !== "") {
      obj.worker = message.worker;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HearthbeatRequest>, I>>(base?: I): HearthbeatRequest {
    return HearthbeatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HearthbeatRequest>, I>>(object: I): HearthbeatRequest {
    const message = createBaseHearthbeatRequest();
    message.worker = object.worker ?? "";
    return message;
  },
};

function createBaseJobInfoRequest(): JobInfoRequest {
  return { jobID: "", workerID: "" };
}

export const JobInfoRequest: MessageFns<JobInfoRequest> = {
  encode(message: JobInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobID !== "") {
      writer.uint32(10).string(message.jobID);
    }
    if (message.workerID !== "") {
      writer.uint32(18).string(message.workerID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseJobInfoRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.jobID = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.workerID = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): JobInfoRequest {
    return {
      jobID: isSet(object.jobID) ? globalThis.String(object.jobID) : "",
      workerID: isSet(object.workerID) ? globalThis.String(object.workerID) : "",
    };
  },

  toJSON(message: JobInfoRequest): unknown {
    const obj: any = {};
    if (message.jobID !== "") {
      obj.jobID = message.jobID;
    }
    if (message.workerID !== "") {
      obj.workerID = message.workerID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobInfoRequest>, I>>(base?: I): JobInfoRequest {
    return JobInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobInfoRequest>, I>>(object: I): JobInfoRequest {
    const message = createBaseJobInfoRequest();
    message.jobID = object.jobID ?? "";
    message.workerID = object.workerID ?? "";
    return message;
  },
};

export type QueueService = typeof QueueService;
export const QueueService = {
  createQueue: {
    path: "/Queue/CreateQueue" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateQueueRequest): Buffer => Buffer.from(CreateQueueRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateQueueRequest => CreateQueueRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
  push: {
    path: "/Queue/Push" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: PushRequest): Buffer => Buffer.from(PushRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PushRequest => PushRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
  listenQueue: {
    path: "/Queue/ListenQueue" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ListenQueueRequest): Buffer => Buffer.from(ListenQueueRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListenQueueRequest => ListenQueueRequest.decode(value),
    responseSerialize: (value: ListenQueueStreamResponse): Buffer =>
      Buffer.from(ListenQueueStreamResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListenQueueStreamResponse => ListenQueueStreamResponse.decode(value),
  },
  deleteQueue: {
    path: "/Queue/DeleteQueue" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteQueueRequest): Buffer => Buffer.from(DeleteQueueRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteQueueRequest => DeleteQueueRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
  hearthbeat: {
    path: "/Queue/Hearthbeat" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HearthbeatRequest): Buffer => Buffer.from(HearthbeatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HearthbeatRequest => HearthbeatRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
  ack: {
    path: "/Queue/Ack" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobInfoRequest): Buffer => Buffer.from(JobInfoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobInfoRequest => JobInfoRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
  error: {
    path: "/Queue/Error" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobInfoRequest): Buffer => Buffer.from(JobInfoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobInfoRequest => JobInfoRequest.decode(value),
    responseSerialize: (value: SuccessBoolResponse): Buffer => Buffer.from(SuccessBoolResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessBoolResponse => SuccessBoolResponse.decode(value),
  },
} as const;

export interface QueueServer extends UntypedServiceImplementation {
  createQueue: handleUnaryCall<CreateQueueRequest, SuccessBoolResponse>;
  push: handleUnaryCall<PushRequest, SuccessBoolResponse>;
  listenQueue: handleServerStreamingCall<ListenQueueRequest, ListenQueueStreamResponse>;
  deleteQueue: handleUnaryCall<DeleteQueueRequest, SuccessBoolResponse>;
  hearthbeat: handleUnaryCall<HearthbeatRequest, SuccessBoolResponse>;
  ack: handleUnaryCall<JobInfoRequest, SuccessBoolResponse>;
  error: handleUnaryCall<JobInfoRequest, SuccessBoolResponse>;
}

export interface QueueClient extends Client {
  createQueue(
    request: CreateQueueRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  createQueue(
    request: CreateQueueRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  createQueue(
    request: CreateQueueRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  push(
    request: PushRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  push(
    request: PushRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  push(
    request: PushRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  listenQueue(
    request: ListenQueueRequest,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ListenQueueStreamResponse>;
  listenQueue(
    request: ListenQueueRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ListenQueueStreamResponse>;
  deleteQueue(
    request: DeleteQueueRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  deleteQueue(
    request: DeleteQueueRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  deleteQueue(
    request: DeleteQueueRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  hearthbeat(
    request: HearthbeatRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  hearthbeat(
    request: HearthbeatRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  hearthbeat(
    request: HearthbeatRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  ack(
    request: JobInfoRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  ack(
    request: JobInfoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  ack(
    request: JobInfoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  error(
    request: JobInfoRequest,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  error(
    request: JobInfoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
  error(
    request: JobInfoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SuccessBoolResponse) => void,
  ): ClientUnaryCall;
}

export const QueueClient = makeGenericClientConstructor(QueueService, "Queue") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): QueueClient;
  service: typeof QueueService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
